---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-photoprism-originals
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-photoprism-originals
  storageClassName: ""
