---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-photoprism-originals
  namespace: photoprism
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-photoprism-originals  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//samba.finnhartshorn.com/sambashare/Photos"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
