---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flare-solverr
  namespace: plex-support
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flare-solverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flare-solverr
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: flare-solverr-config
                optional: false
          image: flaresolverr/flaresolverr
          imagePullPolicy: Always
          name: flare-solverr
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
