---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc-config
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
