---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-calibre-books
  namespace: plex-support
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-calibre-books  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//samba.finnhartshorn.com/sambashare/Books/Calibre Library"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
