---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc-config
  namespace: plex-support
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
