---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghidra-pvc-repo
  namespace: ghidra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2000Mi
