---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-readarr-books
  namespace: plex-support
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-readarr-books
  storageClassName: ""
