---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 5.4.2
    #path: test/test # Need to test using path + valueFiles when pointing to a helm chart repo. + helm.parameters for prod vs dev differences

    chart: calibre
    helm:

      # Release name override (defaults to application name)
      releaseName: calibre

      # Values file as block file
      values: |
        env:
          TZ: "Melbourne/Australia"
        persistence:
          data:
            enabled: true
            storageClass: longhorn
            size: 1Gi
            mountPath: /data
            accessMode: ReadWriteOnce
            existingClaim: pvc-smb-calibre-books
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              hajimari.io/enable: "true"
              hajimari.io/icon: "MenuBook"
              hajimari.io/appName: "Calibre"
            hosts:
              - # -- Host address. Helm template can be passed.
                #host: "calibre.<path:secret/cluster/global#SECRET_DOMAIN>"
                host: "calibre.finnhartshorn.com"
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            ingressClassName: "traefik"
            tls:
              - hosts:
                - "calibre.finnhartshorn.com"
                  #- "calibre.<path:secret/cluster/global#SECRET_DOMAIN>"
                secretName: wilcard-tls

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: plex-support

  syncPolicy: {}
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
