apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-name
  namespace: argocd
spec:
  destination:
    namespace: external-name
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: custom-apps/external-name
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy: {}