apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flare-solverr
  namespace: argocd
spec:
  destination:
    namespace: plex-support
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: custom-apps/flare-solverr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy: {}