apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghidra-server
  namespace: argocd
spec:
  destination:
    namespace: ghidra
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: custom-apps/ghidra-server
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy: {}