---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    repoURL: https://andrenarchy.github.io/helm-charts/
    targetRevision: 14.42.0
    #path: test/test # Need to test using path + valueFiles when pointing to a helm chart repo. + helm.parameters for prod vs dev differences

    chart: home-assistant
    helm:

      # Release name override (defaults to application name)
      releaseName: home-assistant

      # Values file as block file
      values: |
        env:
          TZ: "Melbourne/Australia"
        persistence:
          config:
            enabled: true
            mountPath: /config
            accessMode: ReadWriteOnce
            size: 1Gi
            storageClass: longhorn
        metrics:
          enabled: true

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant

  syncPolicy: {}
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
