---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    repoURL: https://cetic.github.io/helm-charts
    targetRevision: v1.1.3
    #path: test/test # Need to test using path + valueFiles when pointing to a helm chart repo. + helm.parameters for prod vs dev differences

    chart: nifi
    helm:

      # Release name override (defaults to application name)
      releaseName: nifi

      # Values file as block file
      values: |
        replicaCount: 3
        properties:
          sensitiveKey: Hg8YVArihIpyjXoY3O2AkmWI672vAqFyqDmpvpdc
          webProxyHost: nifi.finnhartshorn.com
          isNode: true
        certManager:
          enabled: true
          additionalDnsNames:
          - nifi.finnhartshorn.com
          # caSecrets:
          # - san-cert-secret
          keystorePasswd: dAPLx7HfoG9LgLnvL9Pfel0HR3yIYXVGrhSfJ7X6
          truststorePasswd: utJyMwpFUPGSyw7PHa9bbMjLwd8YAiBr0HjIctUV
        registry:
          enabled: false
          url: https://nifi-registry.nifi.svc.cluster.local
          port: 80
        persistence.enabled: true
        auth:
          singleUser:
            username: finnhartshorn
            password: badpasswordbadpassword
          oidc:
            enabled: true
            clientId: 74436436781a2ca412656a60dc16a1851f3e7420
            clientSecret: 728a25cb5dbff777f3a4d5add362b877cf1f000b213c0a3cfe3345bd139fc0c4389122fd4db30fca7571fede6bb4bcb557980c139900f3d97e125fe3ca17a9af
            claimIdentifyingUser: email
            admin: finnhartshorn@gmail.com
            discoveryUrl: https://auth.finnhartshorn.com/application/o/nifi/.well-known/openid-configuration

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
