---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism-personal
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    path: cluster/custom-apps/photoprism
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: photoprism
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
