apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  destination:
    namespace: plex-support
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: custom-apps/sonarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy: {}