---
apiVersion: v1
kind: Service
metadata:
  name: ghidra
  namespace: ghidra
spec:
  selector:
    app: ghidra
  ports:
  - protocol: TCP
    port: 13100
    targetPort: 13100
  - protocol: TCP
    port: 13101
    targetPort: 13101
  - protocol: TCP
    port: 13102
    targetPort: 13102
  type: LoadBalancer