---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hajimari
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    repoURL: https://hajimari.io
    targetRevision: 2.0.2
    #path: test/test # Need to test using path + valueFiles when pointing to a helm chart repo. + helm.parameters for prod vs dev differences

    chart: hajimari
    helm:

      # Release name override (defaults to application name)
      releaseName: hajimari

      # Values file as block file
      values: |
        hajimari:
          defaultEnable: false
          namespaceSelector:
            any: true
          name: "you"
          customApps:
            - name: Plex
              url: "https://plex.finnhartshorn.com"
              icon: "plex"
            - name: Transmission
              url: "https://transmission.finnhartshorn.com"
              icon: "briefcase-download"
            - name: AdguardHome
              url: "https://adguard.finnhartshorn.com"
              icon: "marker-check"
              hajimari.io/group: "Management"
            - name: Unifi
              url: "https://unifi.finnhartshorn.com"
              icon: "format_underlined_squiggle"
              hajimari.io/group: "Management"
          groups:
            - name: Communicate
              links:
                - name: Discord
                  url: "https://discord.com"
                - name: Gmail
                  url: "https://gmail.com"
                - name: Slack
                  url: "https://slack.com/signin"
            - name: Cloud
              links:
                - name: Box
                  url: "https://box.com"
                - name: Dropbox
                  url: "https://dropbox.com"
                - name: Drive
                  url: "https://drive.google.com"
            - name: Design
              links:
                - name: Awwwards
                  url: "https://awwwards.com"
                - name: Dribbble
                  url: "https://dribbble.com"
                - name: Muz.li
                  url: "https://medium.muz.li/"
            - name: Dev
              links:
                - name: Codepen
                  url: "https://codepen.io/"
                - name: Devdocs
                  url: "https://devdocs.io"
                - name: Devhints
                  url: "https://devhints.io"
            - name: Lifestyle
              links:
                - name: Design Milk
                  url: "https://design-milk.com/category/interior-design/"
                - name: Dwell
                  url: "https://www.dwell.com/"
                - name: Freshome
                  url: "https://www.mymove.com/freshome/"
            - name: Media
              links:
                - name: Spotify
                  url: "http://browse.spotify.com"
                - name: Trakt
                  url: "http://trakt.tv"
                - name: YouTube
                  url: "https://youtube.com/feed/subscriptions"
            - name: Reading
              links:
                - name: Instapaper
                  url: "https://www.instapaper.com/u"
                - name: Medium
                  url: "http://medium.com"
                - name: Reddit
                  url: "http://reddit.com"
            - name: Tech
              links:
                - name: Hacker News
                  url: "https://news.ycombinator.com/"
                - name: The Verge
                  url: "https://theverge.com/"
                - name: MIT Technology Review
                  url: "https://www.technologyreview.com/"
        ingress:
          main:
            enabled: false
        persistence:
          data:
            enabled: true
        podAnnotations:
          configmap.reloader.stakater.com/reload: "hajimari-settings"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi

  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: hajimari

  syncPolicy: {}
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
