---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingressroute
  namespace: plex-support
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "cloud-download"
    hajimari.io/appName: "Prowlarr"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prowlarr.finnhartshorn.com`)
    kind: Rule
    services:
    - name: prowlarr
      port: 9696